package com.pokemmo.core.database.seed

import com.pokemmo.core.database.entity.MoveEntity

object SeedMoves {

    val moves: List<MoveEntity> = listOf(
        // id, name, displayName, typeName, category, power, accuracy, pp, priority, description, generation
        MoveEntity(1,  "pound",        "Pound",          "Normal",   "Physical", 40,  100, 35, 0, "Pounds the foe with forelegs or tail.", 1),
        MoveEntity(10, "hiddenpower",  "Hidden Power",   "Normal",   "Special",  60,  100, 15, 0, "Power and type varies by user.", 2),
        MoveEntity(14, "swords-dance", "Swords Dance",   "Normal",   "Status",   0,   0,   20, 0, "Raises Attack by 2 stages.", 1),
        MoveEntity(15, "cut",          "Cut",            "Normal",   "Physical", 50,  95,  30, 0, "Cuts with sharp claws or scythes.", 1),
        MoveEntity(19, "fly",          "Fly",            "Flying",   "Physical", 90,  95,  15, 0, "Soars into the sky, then attacks next turn.", 1),
        MoveEntity(26, "earthquake",   "Earthquake",     "Ground",   "Physical", 100, 100, 10, 0, "Powerful quake. Double damage underground.", 1),
        MoveEntity(29, "toxic",        "Toxic",          "Poison",   "Status",   0,   90,  10, 0, "Badly poisons the target.", 1),
        MoveEntity(44, "bite",         "Bite",           "Dark",     "Physical", 60,  100, 25, 0, "30% chance to flinch.", 1),
        MoveEntity(53, "flamethrower", "Flamethrower",   "Fire",     "Special",  90,  100, 15, 0, "10% chance to burn.", 1),
        MoveEntity(54, "mist",         "Mist",           "Ice",      "Status",   0,   0,   30, 0, "Protects stat changes for 5 turns.", 1),
        MoveEntity(56, "fissure",      "Fissure",        "Ground",   "Physical", 0,   30,  5,  0, "One-hit KO move.", 1),
        MoveEntity(59, "blizzard",     "Blizzard",       "Ice",      "Special",  110, 70,  5,  0, "10% chance to freeze. Never misses in hail.", 1),
        MoveEntity(68, "counter",      "Counter",        "Fighting", "Physical", 0,   100, 20, -5,"Returns double the physical damage taken.", 1),
        MoveEntity(71, "absorb",       "Absorb",         "Grass",    "Special",  20,  100, 25, 0, "Recovers half of damage dealt.", 1),
        MoveEntity(78, "fire-blast",   "Fire Blast",     "Fire",     "Special",  110, 85,  5,  0, "10% chance to burn.", 1),
        MoveEntity(85, "thunderbolt",  "Thunderbolt",    "Electric", "Special",  90,  100, 15, 0, "10% chance to paralyze.", 1),
        MoveEntity(86, "thunder",      "Thunder",        "Electric", "Special",  110, 70,  10, 0, "30% chance to paralyze. Never misses in rain.", 1),
        MoveEntity(89, "earthquake2",  "Rock Slide",     "Rock",     "Physical", 75,  90,  10, 0, "30% chance to flinch.", 1),
        MoveEntity(94, "psychic",      "Psychic",        "Psychic",  "Special",  90,  100, 10, 0, "10% chance to lower Sp. Def.", 1),
        MoveEntity(99, "rage",         "Bullet Punch",   "Steel",    "Physical", 40,  100, 30, 1, "Priority +1. Always goes first.", 4),
        MoveEntity(110,"recover",      "Recover",        "Normal",   "Status",   0,   0,   10, 0, "Restores up to 50% of max HP.", 1),
        MoveEntity(117,"softboiled",   "Soft-Boiled",    "Normal",   "Status",   0,   0,   10, 0, "Restores up to 50% of max HP.", 1),
        MoveEntity(127,"waterfall",    "Waterfall",      "Water",    "Physical", 80,  100, 15, 0, "20% chance to flinch.", 1),
        MoveEntity(131,"ice-beam",     "Ice Beam",       "Ice",      "Special",  90,  100, 10, 0, "10% chance to freeze.", 1),
        MoveEntity(132,"blizzard2",    "Stone Edge",     "Rock",     "Physical", 100, 80,  5,  0, "High critical-hit ratio.", 4),
        MoveEntity(155,"hydro-pump",   "Hydro Pump",     "Water",    "Special",  110, 80,  5,  0, "Blasts water at extreme power.", 1),
        MoveEntity(157,"toxic2",       "Stealth Rock",   "Rock",     "Status",   0,   0,   20, 0, "Sets pointed stones that hurt entering Pokémon.", 4),
        MoveEntity(162,"sw-dance2",    "Calm Mind",      "Psychic",  "Status",   0,   0,   20, 0, "Raises Sp. Atk and Sp. Def by 1.", 3),
        MoveEntity(165,"struggle",     "Struggle Bug",   "Bug",      "Special",  50,  100, 20, 0, "Lowers target's Sp. Atk.", 5),
        MoveEntity(173,"charm",        "Charm",          "Normal",   "Status",   0,   100, 20, 0, "Harshly lowers target's Attack.", 2),
        MoveEntity(179,"sunny-day",    "Sunny Day",      "Fire",     "Status",   0,   0,   5,  0, "Makes sunlight harsh for 5 turns.", 2),
        MoveEntity(181,"dragon-dance", "Dragon Dance",   "Dragon",   "Status",   0,   0,   20, 0, "Raises Attack and Speed by 1.", 3),
        MoveEntity(182,"attract",      "Wish",           "Normal",   "Status",   0,   0,   10, 0, "User restores HP on the next turn.", 3),
        MoveEntity(185,"rain-dance",   "Rain Dance",     "Water",    "Status",   0,   0,   5,  0, "Makes it rain for 5 turns.", 2),
        MoveEntity(192,"iron-def",     "Iron Defense",   "Steel",    "Status",   0,   0,   15, 0, "Raises Defense by 2.", 3),
        MoveEntity(196,"energy-ball",  "Energy Ball",    "Grass",    "Special",  90,  100, 10, 0, "10% chance to lower Sp. Def.", 4),
        MoveEntity(200,"substitute",   "Substitute",     "Normal",   "Status",   0,   0,   10, 0, "Creates a decoy to take hits.", 1),
        MoveEntity(202,"encore",       "Encore",         "Normal",   "Status",   0,   100, 5,  0, "Forces the foe to repeat its last move.", 2),
        MoveEntity(205,"roost",        "Roost",          "Flying",   "Status",   0,   0,   10, 0, "Heals 50% HP. Removes Flying type temporarily.", 4),
        MoveEntity(207,"outrage",      "Outrage",        "Dragon",   "Physical", 120, 100, 10, 0, "2-3 turns of rampage, then confusion.", 2),
        MoveEntity(210,"bullet-seed",  "Power Whip",     "Grass",    "Physical", 120, 85,  10, 0, "Violently lashes with vines.", 4),
        MoveEntity(214,"shadow-ball",  "Shadow Ball",    "Ghost",    "Special",  80,  100, 15, 0, "20% chance to lower Sp. Def.", 2),
        MoveEntity(218,"rapid-spin",   "Rapid Spin",     "Normal",   "Physical", 20,  100, 40, 0, "Removes entry hazards.", 1),
        MoveEntity(219,"bug-buzz",     "Bug Buzz",       "Bug",      "Special",  90,  100, 10, 0, "10% chance to lower Sp. Def.", 4),
        MoveEntity(224,"magnetic-rise","Spore",          "Grass",    "Status",   0,   100, 15, 0, "Puts the target to sleep.", 1),
        MoveEntity(226,"close-combat", "Close Combat",   "Fighting", "Physical", 120, 100, 5,  0, "Lowers user's Def and Sp. Def by 1.", 4),
        MoveEntity(231,"force-palm",   "Drain Punch",    "Fighting", "Physical", 75,  100, 10, 0, "Recovers half of damage dealt.", 4),
        MoveEntity(241,"twister",      "Dragon Pulse",   "Dragon",   "Special",  85,  100, 10, 0, "Blasts the target with a shock wave.", 4),
        MoveEntity(246,"ancient-power","Ancient Power",  "Rock",     "Special",  60,  100, 5,  0, "10% chance to raise all stats.", 2),
        MoveEntity(258,"toxic-spikes", "Toxic Spikes",   "Poison",   "Status",   0,   0,   20, 0, "Poisons foes that switch in.", 4),
        MoveEntity(269,"leech-seed",   "Leech Seed",     "Grass",    "Status",   0,   90,  10, 0, "Saps HP from the foe each turn.", 1),
        MoveEntity(270,"flash",        "Flash",          "Normal",   "Status",   0,   100, 20, 0, "Lowers target's Accuracy by 1.", 1),
        MoveEntity(279,"power-gem",    "Power Gem",      "Rock",     "Special",  80,  100, 20, 0, "Fires beams of light that are as hard as gems.", 4),
        MoveEntity(283,"spikes",       "Spikes",         "Ground",   "Status",   0,   0,   20, 0, "Lays a trap of spikes at the opponent's feet.", 2),
        MoveEntity(290,"u-turn",       "U-turn",         "Bug",      "Physical", 70,  100, 20, 0, "Attacks then switches out.", 4),
        MoveEntity(309,"trick-room",   "Trick Room",     "Psychic",  "Status",   0,   0,   5,  -7,"Slower Pokémon move first for 5 turns.", 4),
        MoveEntity(337,"earth-power",  "Earth Power",    "Ground",   "Special",  90,  100, 10, 0, "10% chance to lower Sp. Def.", 4),
        MoveEntity(338,"scald",        "Scald",          "Water",    "Special",  80,  100, 15, 0, "30% chance to burn.", 5),
        MoveEntity(339,"wild-charge",  "Wild Charge",    "Electric", "Physical", 90,  100, 15, 0, "User takes 1/4 recoil damage.", 5),
        MoveEntity(347,"low-sweep",    "Low Sweep",      "Fighting", "Physical", 65,  100, 20, 0, "Lowers target's Speed.", 5),
        MoveEntity(349,"freeze-shock", "Ice Punch",      "Ice",      "Physical", 75,  100, 15, 0, "10% chance to freeze.", 1),
        MoveEntity(350,"blaze-kick",   "Fire Punch",     "Fire",     "Physical", 75,  100, 15, 0, "10% chance to burn.", 1),
        MoveEntity(351,"mega-punch",   "Thunder Punch",  "Electric", "Physical", 75,  100, 15, 0, "10% chance to paralyze.", 1),
        MoveEntity(352,"superpower",   "Superpower",     "Fighting", "Physical", 120, 100, 5,  0, "Lowers user's Attack and Defense.", 3),
        MoveEntity(353,"dark-pulse",   "Dark Pulse",     "Dark",     "Special",  80,  100, 15, 0, "20% chance to flinch.", 4),
        MoveEntity(354,"night-shade",  "Night Slash",    "Dark",     "Physical", 70,  100, 15, 0, "High critical-hit ratio.", 4),
        MoveEntity(355,"aura-sphere",  "Aura Sphere",    "Fighting", "Special",  80,  0,   20, 0, "Never misses.", 4),
        MoveEntity(356,"flash-cannon", "Flash Cannon",   "Steel",    "Special",  80,  100, 10, 0, "10% chance to lower Sp. Def.", 4),
        MoveEntity(357,"spore2",       "Giga Drain",     "Grass",    "Special",  75,  100, 10, 0, "Recovers half of damage dealt.", 2),
        MoveEntity(358,"quiver-dance", "Quiver Dance",   "Bug",      "Status",   0,   0,   20, 0, "Raises Sp. Atk, Sp. Def, Speed by 1.", 5),
        MoveEntity(362,"iron-head",    "Iron Head",      "Steel",    "Physical", 80,  100, 15, 0, "30% chance to flinch.", 4),
        MoveEntity(363,"gyro-ball",    "Gyro Ball",      "Steel",    "Physical", 0,   100, 5,  0, "Slower user does more damage.", 4),
        MoveEntity(367,"fury-cutter",  "X-Scissor",      "Bug",      "Physical", 80,  100, 15, 0, "Slashes an X shape.", 4),
        MoveEntity(370,"foul-play",    "Foul Play",      "Dark",     "Physical", 95,  100, 15, 0, "Uses target's Attack stat.", 5),
        MoveEntity(374,"volt-switch",  "Volt Switch",    "Electric", "Special",  70,  100, 20, 0, "Attacks then switches out.", 5),
        MoveEntity(380,"hex",          "Hex",            "Ghost",    "Special",  65,  100, 10, 0, "Double power if target has a status condition.", 5),
        MoveEntity(390,"shift-gear",   "Shift Gear",     "Steel",    "Status",   0,   0,   10, 0, "Raises Attack by 1 and Speed by 2.", 5),
    )
}
